# Generated by Django 5.1.1 on 2025-11-09 02:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="Archive",
        ),
        migrations.AlterModelOptions(
            name="archive",
            options={"verbose_name": "Archive", "verbose_name_plural": "Archives"},
        ),
        migrations.AlterModelTable(
            name="archive",
            table="archive",
        ),
    ]
