# Generated by Django 5.1.1 on 2025-11-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_app", "0002_rename_file_archive_alter_archive_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="archive",
            name="file",
            field=models.FileField(upload_to="uploads/%Y/%m/%d/"),
        ),
    ]
